/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Colorado.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useSnapshot } from "valtio"
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';

export function Colorado(props) {
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)
  const { nodes, materials } = useGLTF('/models/Colorado.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.475, 0.88]} scale={0.394}>
        <mesh geometry={nodes.orange_01_pivot.geometry} material={materials.orange} position={[0, 0, -0.002]} />
      </group>
      <group position={[0, 0.482, 0.923]} scale={0.394}>
        <mesh geometry={nodes.glass_14_pivot.geometry} material={materials.glass} position={[0, 0, -0.001]} />
      </group>
      <group position={[0, 0.684, -0.674]} scale={0.394}>
        <mesh geometry={nodes.black_matt_46_pivot.geometry} material={materials.black_matt} position={[0, 0, 0]} />
      </group>
      <group position={[0, 0.4, 1.027]} scale={0.394}>
        <mesh geometry={nodes.black_shiny_33_pivot.geometry} material={materials.black_shiny} position={[0, 0, 0.001]} />
      </group>
      <group position={[-0.391, 0.099, -0.64]} scale={0.394}>
        <mesh geometry={nodes.black_matt_37_pivot.geometry} material={materials.black_matt} position={[-0.002, 0, 0.002]} />
      </group>
      <group position={[0, 0.663, -0.549]} scale={0.394}>
        <mesh geometry={nodes.black_matt_36_pivot.geometry} material={materials.black_matt} position={[0, 0, -0.001]} />
      </group>
      <group position={[-0.391, 0.099, 0.674]} scale={0.394}>
        <mesh geometry={nodes.black_matt_33_pivot.geometry} material={materials.black_matt} position={[-0.002, 0, 0.002]} />
      </group>
      <group position={[0, 0.255, 0.973]} scale={0.394}>
        <mesh geometry={nodes.black_matt_28_pivot.geometry} material={materials.black_matt} position={[0, 0, 0.001]} />
      </group>
      <group position={[0, 0.368, 0.943]} scale={0.394}>
        <mesh geometry={nodes.black_shiny_18_pivot.geometry} material={materials.black_shiny} position={[0, 0, 0.001]} />
      </group>
      <group position={[0.001, 0.206, -0.475]} scale={0.394}>
        <mesh geometry={nodes.black_matt_27_pivot.geometry} material={materials.black_matt} position={[0, 0, -0.004]} />
      </group>
      <group position={[0, 0.535, 0.091]} scale={0.394}>
        <mesh geometry={nodes.interior_01_pivot.geometry} material={materials.interior} position={[0, 0, -0.001]} />
      </group>
      <group position={[0.391, 0.099, -0.64]} scale={0.394}>
        <mesh geometry={nodes.black_matt_22_pivot.geometry} material={materials.black_matt} position={[0.002, 0, 0.002]} />
      </group>
      <group position={[0, 0.267, -0.998]} scale={0.394}>
        <mesh geometry={nodes.black_matt_21_pivot.geometry} material={materials.black_matt} position={[0, 0, 0.001]} />
      </group>
      <group position={[0, 0.75, -0.04]} scale={0.394}>
        <mesh geometry={nodes.Body.geometry} material={materials.BaseMtl} material-color={snap1.base.BaseMtl} visible={overlay === 1}/>
        <mesh geometry={nodes.Body001.geometry} material={materials.Slaughter} material-color={snap1.base.BaseMtl} visible={overlay === 2}/>
        <mesh geometry={nodes.Body002.geometry} material={materials.BatLady} material-color={snap1.base.BaseMtl} visible={overlay === 3}/>
        <mesh geometry={nodes.Body003.geometry} material={materials.BrakeLine} material-color={snap1.base.BaseMtl} visible={overlay === 4}/>
        <mesh geometry={nodes.Body004.geometry} material={materials.Danger} material-color={snap1.base.BaseMtl} visible={overlay === 5}/>
        <mesh geometry={nodes.Body005.geometry} material={materials.Embers} material-color={snap1.base.BaseMtl} visible={overlay === 6}/>
        <mesh geometry={nodes.Body006.geometry} material={materials.SpiderID} material-color={snap1.base.BaseMtl} visible={overlay === 7}/>
        <mesh geometry={nodes.Body007.geometry} material={materials.Fluid} material-color={snap1.base.BaseMtl} visible={overlay === 8}/>
        <mesh geometry={nodes.Body008.geometry} material={materials.HotRods} material-color={snap1.base.BaseMtl} visible={overlay === 9}/>
        <mesh geometry={nodes.Body009.geometry} material={materials.Mayan} material-color={snap1.base.BaseMtl} visible={overlay === 10}/>
        <mesh geometry={nodes.Body010.geometry} material={materials.SeaBreeze} material-color={snap1.base.BaseMtl} visible={overlay === 11}/>
        <mesh geometry={nodes.Body011.geometry} material={materials.ShapeShifter} material-color={snap1.base.BaseMtl} visible={overlay === 12}/>
        <mesh geometry={nodes.Body012.geometry} material={materials.Silk} material-color={snap1.base.BaseMtl} visible={overlay === 13}/>
        <mesh geometry={nodes.Body013.geometry} material={materials.SnakeSkin} material-color={snap1.base.BaseMtl} visible={overlay === 14}/>
        <mesh geometry={nodes.Body014.geometry} material={materials.Flare} material-color={snap1.base.BaseMtl} visible={overlay === 15}/>
        <mesh geometry={nodes.Body015.geometry} material={materials.Dominator} material-color={snap1.base.BaseMtl} visible={overlay === 16}/>
        <mesh geometry={nodes.Body016.geometry} material={materials.TopGun} material-color={snap1.base.BaseMtl} visible={overlay === 17}/>
        <mesh geometry={nodes.Body017.geometry} material={materials.Explosion} material-color={snap1.base.BaseMtl} visible={overlay === 18}/>
        <mesh geometry={nodes.Body018.geometry} material={materials.WildWest} material-color={snap1.base.BaseMtl} visible={overlay === 19}/>
        <mesh geometry={nodes.Body019.geometry} material={materials.Zombie} material-color={snap1.base.BaseMtl} visible={overlay === 20}/>
      </group>
      <group position={[0, 0.653, 0.416]} scale={0.394}>
        <mesh geometry={nodes.d_glass_01_pivot.geometry} material={materials.d_glass} position={[0, 0.001, 0.001]} />
      </group>
      <group position={[0, 0.481, 0.923]} scale={0.394}>
        <mesh geometry={nodes.chrome_06_pivot.geometry} material={materials.chrome} position={[0, 0, -0.001]} />
      </group>
      <group position={[-0.373, 0.175, -0.526]} scale={0.394}>
        <mesh geometry={nodes.black_matt_19_pivot.geometry} material={materials.black_matt} position={[0, 0.001, 0]} />
      </group>
      <group position={[-0.345, 0.169, -0.594]} scale={0.394}>
        <mesh geometry={nodes.black_matt_18_pivot.geometry} material={materials.black_matt} position={[0, 0.002, 0]} />
      </group>
      <group position={[0.356, 0.174, -0.542]} scale={0.394}>
        <mesh geometry={nodes.silver_d_02_pivot.geometry} material={materials.silver_d} position={[0, -0.001, 0]} />
      </group>
      <group position={[-0.356, 0.173, -0.547]} scale={0.394}>
        <mesh geometry={nodes.black_matt_17_pivot.geometry} material={materials.black_matt} position={[0, 0.002, 0]} />
      </group>
      <group position={[-0.356, 0.174, -0.542]} scale={0.394}>
        <mesh geometry={nodes.silver_d_01_pivot.geometry} material={materials.silver_d} position={[0, -0.001, 0]} />
      </group>
      <group position={[0.356, 0.173, -0.547]} scale={0.394}>
        <mesh geometry={nodes.black_matt_15_pivot.geometry} material={materials.black_matt} position={[0, 0.002, 0]} />
      </group>
      <group position={[0.345, 0.169, -0.594]} scale={0.394}>
        <mesh geometry={nodes.black_matt_13_pivot.geometry} material={materials.black_matt} position={[0, 0.002, 0]} />
      </group>
      <group position={[0, 0.595, 0.397]} scale={0.394}>
        <mesh geometry={nodes.black_matt_06_pivot.geometry} material={materials.black_matt} position={[0, 0.001, 0]} />
      </group>
      <group position={[0.373, 0.175, -0.526]} scale={0.394}>
        <mesh geometry={nodes.black_matt_04_pivot.geometry} material={materials.black_matt} position={[0, 0.001, 0]} />
      </group>
      <group position={[0.391, 0.099, 0.674]} scale={0.394}>
        <mesh geometry={nodes.black_matt_02_pivot.geometry} material={materials.black_matt} position={[0.002, 0, 0.002]} />
      </group>
      <group position={[0, 0.28, -0.991]} scale={0.394}>
        <mesh geometry={nodes.black_matt_11_pivot.geometry} material={materials.black_matt} position={[0, 0, 0.001]} />
      </group>
      <group position={[0, 0.659, -0.365]} scale={0.394}>
        <mesh geometry={nodes.black_matt_10_pivot.geometry} material={materials.black_matt} position={[0, 0.001, 0]} />
      </group>
      <group position={[0, 0.469, 0.918]} scale={0.394}>
        <mesh geometry={nodes.black_shiny_03_pivot.geometry} material={materials.black_shiny} position={[0, 0, 0.001]} />
      </group>
      <group position={[0, 0.341, 0.704]} scale={0.394}>
        <mesh geometry={nodes.black_matt_07_pivot.geometry} material={materials.black_matt} position={[0, 0, 0.001]} />
      </group>
      <mesh geometry={nodes.interior_03.geometry} material={materials.interior} position={[0, 0.459, 0.399]} scale={0.394} />
      <mesh geometry={nodes.black_06.geometry} material={materials.black} position={[0, 0.312, 0.982]} scale={0.394} />
      <mesh geometry={nodes.red_11.geometry} material={materials.red} position={[0, 0.2, 0.99]} scale={0.394} />
      <mesh geometry={nodes.chrome_25.geometry} material={materials.chrome} position={[0, 0.487, 0.984]} scale={0.394} />
      <mesh geometry={nodes.o_glass_01.geometry} material={materials.o_glass} position={[0, 0.487, 0.989]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_48.geometry} material={materials.black_shiny} position={[0.001, 0.437, 1.046]} scale={0.394} />
      <mesh geometry={nodes.chrome_24.geometry} material={materials.chrome} position={[0.001, 0.437, 1.056]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_47.geometry} material={materials.black_shiny} position={[0.001, 0.437, 1.058]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_46.geometry} material={materials.black_shiny} position={[0, 0.271, -1.073]} scale={0.394} />
      <mesh geometry={nodes.black_matt_58.geometry} material={materials.black_matt} position={[0, 0.225, -1.068]} scale={0.394} />
      <mesh geometry={nodes.black_matt_57.geometry} material={materials.black_matt} position={[0, 0.272, -1.063]} scale={0.394} />
      <mesh geometry={nodes.silver_12.geometry} material={materials.silver} position={[-0.035, 0.529, -1.058]} scale={0.394} />
      <mesh geometry={nodes.black_matt_56.geometry} material={materials.black_matt} position={[0, 0.534, -1.058]} scale={0.394} />
      <mesh geometry={nodes.glass_17.geometry} material={materials.glass} position={[0, 0.292, -1.051]} scale={0.394} />
      <mesh geometry={nodes.chrome_23.geometry} material={materials.chrome} position={[0, 0.291, -1.051]} scale={0.394} />
      <mesh geometry={nodes.glass_16.geometry} material={materials.glass} position={[0, 0.293, -1.051]} scale={0.394} />
      <mesh geometry={nodes.black_matt_55.geometry} material={materials.black_matt} position={[0, 0.585, -1.048]} scale={0.394} />
      <mesh geometry={nodes.red_10.geometry} material={materials.red} position={[0, 0.744, -0.362]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_45.geometry} material={materials.black_shiny} position={[0.226, 0.363, -1.043]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_44.geometry} material={materials.black_shiny} position={[0, 0.5, 0.867]} scale={0.394} />
      <mesh geometry={nodes.glass_13.geometry} material={materials.glass} position={[0, 0.403, -1.033]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_43.geometry} material={materials.black_shiny} position={[0, 0.474, 0.923]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_42.geometry} material={materials.black_shiny} position={[0, 0.469, 0.905]} scale={0.394} />
      <mesh geometry={nodes.black_matt_54.geometry} material={materials.black_matt} position={[0, 0.578, -1.032]} scale={0.394} />
      <mesh geometry={nodes.glass_12.geometry} material={materials.glass} position={[0, 0.403, -1.029]} scale={0.394} />
      <mesh geometry={nodes.body_12.geometry} material={materials.body} position={[0, 0.337, -1.029]} scale={0.394} />
      <mesh geometry={nodes.black_matt_53.geometry} material={materials.black_matt} position={[0.092, 0.301, -1.027]} scale={0.394} />
      <mesh geometry={nodes.chrome_20.geometry} material={materials.chrome} position={[0, 0.678, 0.326]} scale={0.394} />
      <mesh geometry={nodes.chrome_19.geometry} material={materials.chrome} position={[0, 0.403, -1.023]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_41.geometry} material={materials.black_shiny} position={[0, 0.403, -1.022]} scale={0.394} />
      <mesh geometry={nodes.orange_02.geometry} material={materials.orange} position={[0, 0.475, 0.881]} scale={0.394} />
      <mesh geometry={nodes.chrome_26.geometry} material={materials.chrome} position={[0, 0.484, 0.94]} scale={0.394} />
      <mesh geometry={nodes.interior_04.geometry} material={materials.interior} position={[0, 0.681, 0.336]} scale={0.394} />
      <mesh geometry={nodes.black_matt_49.geometry} material={materials.black_matt} position={[0, 0.576, -0.698]} scale={0.394} />
      <mesh geometry={nodes.r_glass_03.geometry} material={materials.r_glass} position={[0, 0.459, -1]} scale={0.394} />
      <mesh geometry={nodes.silver_11.geometry} material={materials.silver} position={[-0.228, 0.204, -0.823]} scale={0.394} />
      <mesh geometry={nodes.black_matt_48.geometry} material={materials.black_matt} position={[0, 0.379, -0.702]} scale={0.394} />
      <mesh geometry={nodes.glass_10.geometry} material={materials.glass} position={[0, 0.469, 0.925]} scale={0.394} />
      <mesh geometry={nodes.chrome_16.geometry} material={materials.chrome} position={[0, 0.469, 0.94]} scale={0.394} />
      <mesh geometry={nodes.body_11.geometry} material={materials.body} position={[0, 0.227, 0.105]} scale={0.394} />
      <mesh geometry={nodes.chrome_15.geometry} material={materials.chrome} position={[0, 0.25, 1.062]} scale={0.394} />
      <mesh geometry={nodes.black_matt_47.geometry} material={materials.black_matt} position={[0, 0.331, 0.951]} scale={0.394} />
      <mesh geometry={nodes.chrome_17.geometry} material={materials.chrome} position={[0, 0.405, -1.015]} scale={0.394} />
      <mesh geometry={nodes.black_matt_50.geometry} material={materials.black_matt} position={[0, 0.477, -1.008]} scale={0.394} />
      <mesh geometry={nodes.chrome_14.geometry} material={materials.chrome} position={[-0.386, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.red_07.geometry} material={materials.red} position={[0.001, 0.437, 1.057]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_34.geometry} material={materials.black_shiny} position={[0, 0.492, 0.727]} scale={0.394} />
      <mesh geometry={nodes.chrome_13.geometry} material={materials.chrome} position={[-0.386, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.brakes1_04.geometry} material={materials.brakes1} position={[-0.356, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_matt_42.geometry} material={materials.black_matt} position={[0, 0.478, 1.007]} scale={0.394} />
      <mesh geometry={nodes.chrome_12.geometry} material={materials.chrome} position={[0, 0.25, 1.064]} scale={0.394} />
      <mesh geometry={nodes.interior_02.geometry} material={materials.interior} position={[0, 0.485, 0.09]} scale={0.394} />
      <mesh geometry={nodes.glass_08.geometry} material={materials.glass} position={[0, 0.25, 1.064]} scale={0.394} />
      <mesh geometry={nodes.brakes1_03.geometry} material={materials.brakes1} position={[0.356, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.chrome_11.geometry} material={materials.chrome} position={[0, 0.744, -0.362]} scale={0.394} />
      <mesh geometry={nodes.red_06.geometry} material={materials.red} position={[0, 0.468, -0.984]} scale={0.394} />
      <mesh geometry={nodes.silver_08.geometry} material={materials.silver} position={[0.386, 0.492, 0.071]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_26.geometry} material={materials.black_shiny} position={[-0.405, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.brakes1_02.geometry} material={materials.brakes1} position={[-0.356, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.silver_d_04.geometry} material={materials.silver_d} position={[-0.356, 0.174, 0.658]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_22.geometry} material={materials.black_shiny} position={[-0.348, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_20.geometry} material={materials.black_shiny} position={[-0.405, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_matt_34.geometry} material={materials.black_matt} position={[-0.356, 0.173, 0.663]} scale={0.394} />
      <mesh geometry={nodes.black_matt_32.geometry} material={materials.black_matt} position={[-0.345, 0.169, 0.711]} scale={0.394} />
      <mesh geometry={nodes.black_05.geometry} material={materials.black} position={[0, 0.197, 1.007]} scale={0.394} />
      <mesh geometry={nodes.black_matt_31.geometry} material={materials.black_matt} position={[0, 0.385, 1.012]} scale={0.394} />
      <mesh geometry={nodes.plate_02.geometry} material={materials.plate} position={[0, 0.304, -1.026]} scale={0.394} />
      <mesh geometry={nodes.plate_01.geometry} material={materials.plate} position={[0, 0.263, 1.083]} scale={0.394} />
      <mesh geometry={nodes.black_matt_26.geometry} material={materials.black_matt} position={[0, 0.369, 0.92]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_17.geometry} material={materials.black_shiny} position={[-0.348, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_04.geometry} material={materials.black} position={[0, 0.367, -0.011]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_16.geometry} material={materials.black_shiny} position={[0.405, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_matt_24.geometry} material={materials.black_matt} position={[0.356, 0.173, 0.663]} scale={0.394} />
      <mesh geometry={nodes.black_matt_23.geometry} material={materials.black_matt} position={[0.373, 0.174, 0.643]} scale={0.394} />
      <mesh geometry={nodes.chrome_07.geometry} material={materials.chrome} position={[0.386, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.silver_04.geometry} material={materials.silver} position={[0, 0.174, 0.995]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_08.geometry} material={materials.black_shiny} position={[0, 0.475, -1.057]} scale={0.394} />
      <mesh geometry={nodes.glass_04.geometry} material={materials.glass} position={[0, 0.744, -0.365]} scale={0.394} />
      <mesh geometry={nodes.glass_03.geometry} material={materials.glass} position={[0, 0.744, -0.369]} scale={0.394} />
      <mesh geometry={nodes.r_glass_02.geometry} material={materials.r_glass} position={[0, 0.744, -0.368]} scale={0.394} />
      <mesh geometry={nodes.black_matt_20.geometry} material={materials.black_matt} position={[0, 0.488, -0.381]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_06.geometry} material={materials.black_shiny} position={[0.405, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.brakes1_01.geometry} material={materials.brakes1} position={[0.356, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.glass_01.geometry} material={materials.glass} position={[0, 0.801, -0.401]} scale={0.394} />
      <mesh geometry={nodes.black_matt_05.geometry} material={materials.black_matt} position={[0.167, 0.437, 1.03]} scale={0.394} />
      <mesh geometry={nodes.chrome_04.geometry} material={materials.chrome} position={[0.386, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_02.geometry} material={materials.black_shiny} position={[0.386, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.white_01.geometry} material={materials.white} position={[0, 0.493, 0.74]} scale={0.394} />
      <mesh geometry={nodes.red_01.geometry} material={materials.red} position={[-0.27, 0.365, -1.041]} scale={0.394} />
      <mesh geometry={nodes.chrome_02.geometry} material={materials.chrome} position={[0, 0.603, -0.534]} scale={0.394} />
      <mesh geometry={nodes.black_matt_03.geometry} material={materials.black_matt} position={[0.345, 0.169, 0.711]} scale={0.394} />
      <mesh geometry={nodes.black_matt_01.geometry} material={materials.black_matt} position={[0, 0.204, 0.061]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_05.geometry} material={materials.black_shiny} position={[0.386, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.r_glass_01.geometry} material={materials.r_glass} position={[0, 0.744, -0.365]} scale={0.394} />
      <mesh geometry={nodes.black_matt_09.geometry} material={materials.black_matt} position={[0, 0.295, -1.046]} scale={0.394} />
      <mesh geometry={nodes.black_matt_08.geometry} material={materials.black_matt} position={[0, 0.659, -0.366]} scale={0.394} />
      <mesh geometry={nodes.red_04.geometry} material={materials.red} position={[0, 0.476, -1.019]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_50_pivot.geometry} material={materials.black_shiny} position={[0.001, 0.226, -0.843]} rotation={[0.068, 0, -Math.PI / 2]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_35_pivot.geometry} material={materials.black_shiny} position={[0, 0.475, 0.869]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_49_pivot.geometry} material={materials.black_shiny} position={[0, 0.586, 0.39]} scale={0.394} />
      <mesh geometry={nodes.glass_15_pivot.geometry} material={materials.glass} position={[0, 0.293, -1.051]} scale={0.394} />
      <mesh geometry={nodes.chrome_22_pivot.geometry} material={materials.chrome} position={[0, 0.293, -1.051]} scale={0.394} />
      <mesh geometry={nodes.black_matt_52_pivot.geometry} material={materials.black_matt} position={[0, 0.714, 0.334]} scale={0.394} />
      <mesh geometry={nodes.black_matt_51_pivot.geometry} material={materials.black_matt} position={[0, 0.576, 0.539]} scale={0.394} />
      <mesh geometry={nodes.d_glass_02_pivot.geometry} material={materials.d_glass} position={[0, 0.641, 0.219]} scale={0.394} />
      <mesh geometry={nodes.chrome_18_pivot.geometry} material={materials.chrome} position={[0, 0.578, 0.373]} scale={0.394} />
      <mesh geometry={nodes.r_lights_01_pivot.geometry} material={materials.r_lights} position={[0, 0.462, -1.022]} scale={0.394} />
      <mesh geometry={nodes.r_glass_06_pivot.geometry} material={materials.r_glass} position={[0, 0.462, -1.022]} scale={0.394} />
      <mesh geometry={nodes.tire_05_pivot.geometry} material={materials.tire} position={[0.001, 0.228, -0.843]} rotation={[0.068, 0, -Math.PI / 2]} scale={0.394} />
      <mesh geometry={nodes.r_glass_07_pivot.geometry} material={materials.r_glass} position={[0, 0.747, -0.366]} scale={0.394} />
      <mesh geometry={nodes.red_12_pivot.geometry} material={materials.red} position={[0, 0.747, -0.366]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_51_pivot.geometry} material={materials.black_shiny} position={[0, 0.475, 0.359]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_39_pivot.geometry} material={materials.black_shiny} position={[-0.169, 0.583, 0.538]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_38_pivot.geometry} material={materials.black_shiny} position={[0, 0.495, 0.908]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_37_pivot.geometry} material={materials.black_shiny} position={[0.146, 0.575, 0.568]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_36_pivot.geometry} material={materials.black_shiny} position={[0.088, 0.583, 0.552]} scale={0.394} />
      <mesh geometry={nodes.glass_09_pivot.geometry} material={materials.glass} position={[0, 0.469, 0.946]} scale={0.394} />
      <mesh geometry={nodes.glass_11_pivot.geometry} material={materials.glass} position={[0, 0.405, -1.018]} scale={0.394} />
      <mesh geometry={nodes.r_glass_05_pivot.geometry} material={materials.r_glass} position={[0, 0.475, -1.006]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_40_pivot.geometry} material={materials.black_shiny} position={[0, 0.275, -1.006]} scale={0.394} />
      <mesh geometry={nodes.red_08_pivot.geometry} material={materials.red} position={[0, 0.475, -1.003]} scale={0.394} />
      <mesh geometry={nodes.silver_10_pivot.geometry} material={materials.silver} position={[-0.403, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_32_pivot.geometry} material={materials.black_shiny} position={[-0.383, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_matt_45_pivot.geometry} material={materials.black_matt} position={[0, 0.241, -0.325]} scale={0.394} />
      <mesh geometry={nodes.black_matt_44_pivot.geometry} material={materials.black_matt} position={[0, 0.238, -0.015]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_31_pivot.geometry} material={materials.black_shiny} position={[-0.386, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_matt_43_pivot.geometry} material={materials.black_matt} position={[0, 0.48, 1.009]} scale={0.394} />
      <mesh geometry={nodes.black_matt_41_pivot.geometry} material={materials.black_matt} position={[0, 0.341, 1.085]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_30_pivot.geometry} material={materials.black_shiny} position={[-0.391, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.glass_07_pivot.geometry} material={materials.glass} position={[0, 0.25, 1.067]} scale={0.394} />
      <mesh geometry={nodes.black_matt_39_pivot.geometry} material={materials.black_matt} position={[0, 0.744, -0.047]} scale={0.394} />
      <mesh geometry={nodes.vd_glass_03_pivot.geometry} material={materials.vd_glass} position={[0, 0.645, -0.153]} scale={0.394} />
      <mesh geometry={nodes.black_matt_38_pivot.geometry} material={materials.black_matt} position={[0, 0.808, -0.317]} scale={0.394} />
      <mesh geometry={nodes.glass_06_pivot.geometry} material={materials.glass} position={[0, 0.469, 0.916]} scale={0.394} />
      <mesh geometry={nodes.glass_05_pivot.geometry} material={materials.glass} position={[0, 0.495, 0.923]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_29_pivot.geometry} material={materials.black_shiny} position={[-0.118, 0.575, 0.572]} scale={0.394} />
      <mesh geometry={nodes.red_05_pivot.geometry} material={materials.red} position={[0, 0.468, -0.983]} scale={0.394} />
      <mesh geometry={nodes.tire_04_pivot.geometry} material={materials.tire} position={[-0.349, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.tire_03_pivot.geometry} material={materials.tire} position={[-0.349, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.tire_02_pivot.geometry} material={materials.tire} position={[0.349, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.tire_01_pivot.geometry} material={materials.tire} position={[0.349, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.silver_09_pivot.geometry} material={materials.silver} position={[-0.403, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.silver_07_pivot.geometry} material={materials.silver} position={[0.381, 0.491, 0.053]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_28_pivot.geometry} material={materials.black_shiny} position={[-0.391, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_27_pivot.geometry} material={materials.black_shiny} position={[-0.383, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_25_pivot.geometry} material={materials.black_shiny} position={[-0.384, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_24_pivot.geometry} material={materials.black_shiny} position={[0, 0.567, 0.756]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_23_pivot.geometry} material={materials.black_shiny} position={[0.384, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_21_pivot.geometry} material={materials.black_shiny} position={[-0.386, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_19_pivot.geometry} material={materials.black_shiny} position={[-0.384, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_matt_35_pivot.geometry} material={materials.black_matt} position={[-0.373, 0.174, 0.643]} scale={0.394} />
      <mesh geometry={nodes.black_matt_30_pivot.geometry} material={materials.black_matt} position={[0, 0.286, 0.674]} scale={0.394} />
      <mesh geometry={nodes.black_matt_29_pivot.geometry} material={materials.black_matt} position={[0, 0.259, 1.054]} scale={0.394} />
      <mesh geometry={nodes.chrome_09_pivot.geometry} material={materials.chrome} position={[0, 0.25, 1.064]} scale={0.394} />
      <mesh geometry={nodes.silver_06_pivot.geometry} material={materials.silver} position={[0, 0.172, 0.955]} scale={0.394} />
      <mesh geometry={nodes.black_matt_25_pivot.geometry} material={materials.black_matt} position={[0, 0.572, 0.048]} scale={0.394} />
      <mesh geometry={nodes.silver_d_03_pivot.geometry} material={materials.silver_d} position={[0.356, 0.174, 0.658]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_15_pivot.geometry} material={materials.black_shiny} position={[0.348, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_14_pivot.geometry} material={materials.black_shiny} position={[0.348, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_13_pivot.geometry} material={materials.black_shiny} position={[0.383, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_12_pivot.geometry} material={materials.black_shiny} position={[0.391, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.silver_05_pivot.geometry} material={materials.silver} position={[0.403, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_11_pivot.geometry} material={materials.black_shiny} position={[0.384, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_10_pivot.geometry} material={materials.black_shiny} position={[0.391, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_09_pivot.geometry} material={materials.black_shiny} position={[0.383, 0.169, 0.715]} scale={0.394} />
      <mesh geometry={nodes.silver_03_pivot.geometry} material={materials.silver} position={[0.154, 0.437, 1.038]} scale={0.394} />
      <mesh geometry={nodes.black_03_pivot.geometry} material={materials.black} position={[0, 0.288, -0.964]} scale={0.394} />
      <mesh geometry={nodes.glass_02_pivot.geometry} material={materials.glass} position={[0, 0.747, -0.369]} scale={0.394} />
      <mesh geometry={nodes.vd_glass_02_pivot.geometry} material={materials.vd_glass} position={[0, 0.659, -0.368]} scale={0.394} />
      <mesh geometry={nodes.black_02_pivot.geometry} material={materials.black} position={[0, 0.653, 0.416]} scale={0.394} />
      <mesh geometry={nodes.black_01_pivot.geometry} material={materials.black} position={[0, 0.659, -0.369]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_07_pivot.geometry} material={materials.black_shiny} position={[0, 0.482, 0.922]} scale={0.394} />
      <mesh geometry={nodes.black_matt_16_pivot.geometry} material={materials.black_matt} position={[0, 0.647, 0.044]} scale={0.394} />
      <mesh geometry={nodes.black_matt_14_pivot.geometry} material={materials.black_matt} position={[0, 0.349, -0.639]} scale={0.394} />
      <mesh geometry={nodes.red_03_pivot.geometry} material={materials.red} position={[0, 0.461, -1.012]} scale={0.394} />
      <mesh geometry={nodes.silver_01_pivot.geometry} material={materials.silver} position={[-0.24, 0.365, -1.044]} scale={0.394} />
      <mesh geometry={nodes.red_02_pivot.geometry} material={materials.red} position={[0.192, 0.437, 1.033]} scale={0.394} />
      <mesh geometry={nodes.vd_glass_01_pivot.geometry} material={materials.vd_glass} position={[0, 0.762, 0.117]} scale={0.394} />
      <mesh geometry={nodes.chrome_03_pivot.geometry} material={materials.chrome} position={[-0.25, 0.365, -1.042]} scale={0.394} />
      <mesh geometry={nodes.chrome_01_pivot.geometry} material={materials.chrome} position={[0.167, 0.437, 1.036]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_01_pivot.geometry} material={materials.black_shiny} position={[0, 0.793, -0.413]} scale={0.394} />
      <mesh geometry={nodes.black_matt_12_pivot.geometry} material={materials.black_matt} position={[0, 0.477, -0.688]} scale={0.394} />
      <mesh geometry={nodes.silver_02_pivot.geometry} material={materials.silver} position={[0.403, 0.169, -0.599]} scale={0.394} />
      <mesh geometry={nodes.body_04_pivot.geometry} material={materials.body} position={[0, 0.493, -0.078]} scale={0.394} />
      <mesh geometry={nodes.black_shiny_04_pivot.geometry} material={materials.black_shiny} position={[0, 0.462, 0.932]} scale={0.394} />
      <mesh geometry={nodes.chrome_05_pivot.geometry} material={materials.chrome} position={[0, 0.747, -0.367]} scale={0.394} />
      <mesh geometry={nodes.d_red_01_pivot.geometry} material={materials.d_red} position={[0, 0.459, -0.999]} scale={0.394} />
    </group>
  )
}

useGLTF.preload('/models/Colorado.glb')
